### ISSUE TITLE
Spring Security 설정

### ISSUE THREAD

**Issue by JadeKim042386** [fresh-trash-project/fresh-trash-backend#1]

**Comment by velyvelylovely** [comment]
## 어떤 기능인가요?

- Spring Security를 활용하여 애플리케이션의 보안을 강화하는 기능

## 작업 상세 내용

- [ ] Spring Security 의존성 추가
- [ ] WebSecurityConfigurerAdapter를 상속받아 보안 설정 커스터마이징
- [ ] 인증을 위한 UserDetailsService 구현
- [ ] 패스워드 인코딩을 위한 PasswordEncoder 빈 등록
- [ ] CSRF, CORS 설정 조정
- [ ] 인증과 관련된 HTTP 경로 설정 (보호할 경로와 보호하지 않을 경로 구분)
- [ ] 권한에 따른 접근 제어 설정
- [ ] 테스트 코드 작성

## 참고할 만한 자료(선택)

- 공식 Spring Security 문서: https://spring.io/projects/spring-security
- Spring Security를 이용한 JWT 토큰 기반 인증: https://jwt.io/
- OAuth2 공식 문서: https://oauth.net/2/
